name: Validate - Accessibility

on:
  workflow_dispatch:
    inputs:
      domain_prefix:
        type: choice
        description: 'Domain prefix to run against'
        required: true
        default: 'test'
        options:
          - 'test'
          - 'staging'
          - 'www'
jobs:
  accessibility_scan:
    name: 'Run Pa11y Accessibility Scan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: ./src/e2e/pa11y

      - name: Run accessibility scans
        working-directory: ./src/e2e/pa11y
        run: yarn pa11y-ci --config pa11y.json --sitemap https://${{ github.event.inputs.domain_prefix }}.support-for-care-leavers.education.gov.uk/sitemap.xml
