name: Validate - Apps

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/validate-apps.yaml'

jobs:
  build-backend:
    name: 'Build Web'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: .

# Temporarily disabled these until work starts on the new frontend and admin projects
#      - name: Run Frontend Gulp Dev
#        working-directory: ./src/Frontend
#        run: gulp dev
#
#      - name: Run Admin Gulp Dev
#        working-directory: ./src/Admin
#        run: gulp dev

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
#          cache: true

      - name: Restore dependencies
        working-directory: .
        run: dotnet restore --locked-mode

      - name: Build Solution
        working-directory: .
        run: dotnet build --no-restore

      - name: Run Integration Tests
        working-directory: .
        run: dotnet test --no-build --verbosity normal