name: Validate - E2E Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'src/e2e/gtaa.e2etests/**'
      - '.github/workflows/validate-apps.yaml'
      - '.github/workflows/validate-e2e.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/e2e/gtaa.e2etests/**'
      - '.github/workflows/validate-apps.yaml'
      - '.github/workflows/validate-e2e.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Playwright Tests
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

#      Might need a separate docker build step for images to utilise tagging
#      - name: Build Api Docker Docker Image
#        id: build
#        working-directory: ./src
#        run: docker build . -t gtaa-web-api:e2e -f Api/Dockerfile

      - name: Run E2E Docker Image
        id: run
        working-directory: ./src
        env:
          DEFAULT_CONNECTION_STRING: ${{ secrets.DEFAULT_CONNECTION_STRING }}
          SQLSERVER_SA_PASSWORD: ${{ secrets.SQLSERVER_SA_PASSWORD }}
        run: docker compose -f Infrastructure/compose-ci.yaml up -d
        
        # When Frontend work is underway, uncomment the following steps to run E2E tests
#      - name: Install dependencies
#        working-directory: ./src/e2e/CareLeavers.E2ETests
#        run: yarn install
#
#      - name: Install Playwright Browsers
#        working-directory: ./src/e2e/CareLeavers.E2ETests
#        run: yarn playwright install --with-deps
#
#      - name: Run Playwright Tests
#        if: steps.run.outcome == 'success'
#        working-directory: ./src/e2e/CareLeavers.E2ETests
#        run: yarn playwright test -c playwright-ci.config.ts
#
#      - name: Upload Playwright Test Report
#        if: always() 
#        uses: actions/upload-artifact@v4
#        with:
#          name: playwright-report
#          path: ./src/e2e/CareLeavers.E2ETests/playwright-report/
#          if-no-files-found: ignore
#          
#      - name: Upload Screenshots on Failure
#        if: failure()
#        uses: actions/upload-artifact@v4
#        with:
#          name: playwright-screenshots
#          path: ./src/e2e/CareLeavers.E2ETests/test-results/screenshots/
